"""LLM service for script and image prompt generation using Claude API."""

import json
from typing import Optional

import httpx

from config import get_settings

settings = get_settings()

VIDEO_STYLE_DESCRIPTIONS = {
    "presenter": "Direct presenter to camera. Trust-building, personal connection. Good for services and coaching.",
    "product": "Fast cuts, bold visuals, product-focused shots. Built for e-commerce and physical products.",
    "animated": "Clean animated explainer style. Works for apps, tools, SaaS, and complex concepts.",
    "voiceover": "Professional voiceover with B-roll footage. No on-camera talent needed.",
    "hybrid": "Mix of formats. Combine presenter segments with product shots or B-roll.",
}

VIDEO_LENGTH_SPECS = {
    "6s": {"duration": 6, "scenes": "2-3", "description": "Quick bumper/teaser. Hook + single message."},
    "15s": {"duration": 15, "scenes": "3-4", "description": "Standard social format. Hook + key points + CTA."},
    "30s": {"duration": 30, "scenes": "5-7", "description": "Extended story. Hook + problem + solution + proof + CTA."},
}

SCRIPT_PROMPT = """You are a short-form video scriptwriter for Dutch small businesses.

CLIENT CONTEXT:
- Business: {business_name}
- Offer: {what_they_sell}
- Audience: {target_customer}
- Differentiator: {what_makes_different}
- Tone: {tone}
- Language: {language}
- Topic focus: {topic}

VIDEO SPECS:
- Style: {video_style} — {video_style_description}
- Length: {video_length} ({video_length_description})
- Target scenes: {target_scenes}

TASK:
Write a {video_length} video script for Instagram Reels / TikTok.

REQUIREMENTS:
- Strong hook in first 2 seconds
- Clear single message
- Call to action at end
- {language} language
- {tone} tone
- Exactly {target_scenes} scenes to fit {video_length} duration
- Match the {video_style} style in scene descriptions

OUTPUT FORMAT:
Return ONLY valid JSON with no additional text:
{{
  "hook": "Opening line (2-3 seconds)",
  "scenes": [
    {{"text": "Scene 1 narration", "visual": "Brief visual direction for this scene", "duration": 5}},
    {{"text": "Scene 2 narration", "visual": "Brief visual direction for this scene", "duration": 6}}
  ],
  "cta": "Closing call to action",
  "total_duration": {target_duration}
}}"""

IMAGE_STYLE_DIRECTIONS = {
    "presenter": "Professional person speaking directly to camera, well-lit, confident pose, business casual attire",
    "product": "Product-focused shots, clean backgrounds, dynamic angles, hero lighting, e-commerce style",
    "animated": "Clean vector illustration style, flat design, modern minimalist, soft colors",
    "voiceover": "Cinematic B-roll footage, lifestyle scenes, atmospheric lighting, stock footage aesthetic",
    "hybrid": "Mix of styles as appropriate for each scene",
}

IMAGE_PROMPT_TEMPLATE = """You are a visual director for short-form video content.

SCRIPT:
{script_json}

BRAND CONTEXT:
- Industry: {industry}
- Video Style: {video_style}
- Visual Direction: {visual_direction}

TASK:
Generate an image prompt for each scene. Images will be generated by Flux.

REQUIREMENTS:
- Match the {video_style} style consistently
- {visual_direction}
- No text in images
- Consistent visual style across all scenes
- Safe for work
- Appropriate for Dutch business audience
- 9:16 vertical format composition

OUTPUT FORMAT:
Return ONLY valid JSON with no additional text:
{{
  "prompts": [
    {{"scene": 1, "prompt": "Detailed image prompt for scene 1..."}},
    {{"scene": 2, "prompt": "Detailed image prompt for scene 2..."}}
  ]
}}"""


async def generate_script(
    business_name: str,
    what_they_sell: str,
    target_customer: str,
    what_makes_different: str,
    tone: str = "friendly",
    language: str = "EN",
    topic: Optional[str] = None,
    video_style: str = "voiceover",
    video_length: str = "15s",
) -> dict:
    """
    Generate a video script using Claude API.

    Returns the script as a structured dict.
    """
    if not settings.anthropic_api_key:
        raise ValueError("ANTHROPIC_API_KEY not configured")

    # Get style and length specs
    style_desc = VIDEO_STYLE_DESCRIPTIONS.get(video_style, VIDEO_STYLE_DESCRIPTIONS["voiceover"])
    length_spec = VIDEO_LENGTH_SPECS.get(video_length, VIDEO_LENGTH_SPECS["15s"])

    prompt = SCRIPT_PROMPT.format(
        business_name=business_name,
        what_they_sell=what_they_sell,
        target_customer=target_customer,
        what_makes_different=what_makes_different,
        tone=tone,
        language=language,
        topic=topic or "general introduction",
        video_style=video_style,
        video_style_description=style_desc,
        video_length=video_length,
        video_length_description=length_spec["description"],
        target_scenes=length_spec["scenes"],
        target_duration=length_spec["duration"],
    )

    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": settings.anthropic_api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 1000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60.0,
        )
        response.raise_for_status()

    result = response.json()
    content = result["content"][0]["text"]

    # Parse JSON from response
    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse script JSON: {e}\nContent: {content}")


async def generate_image_prompts(
    script: dict,
    industry: str = "general business",
    video_style: str = "voiceover",
) -> list[dict]:
    """
    Generate image prompts for each scene in a script.

    Returns a list of {scene, prompt} dicts.
    """
    if not settings.anthropic_api_key:
        raise ValueError("ANTHROPIC_API_KEY not configured")

    visual_direction = IMAGE_STYLE_DIRECTIONS.get(
        video_style, IMAGE_STYLE_DIRECTIONS["voiceover"]
    )

    prompt = IMAGE_PROMPT_TEMPLATE.format(
        script_json=json.dumps(script, indent=2),
        industry=industry,
        video_style=video_style,
        visual_direction=visual_direction,
    )

    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": settings.anthropic_api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 2000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60.0,
        )
        response.raise_for_status()

    result = response.json()
    content = result["content"][0]["text"]

    # Parse JSON from response
    try:
        data = json.loads(content)
        return data.get("prompts", [])
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse image prompts JSON: {e}\nContent: {content}")
