"""LLM service for script and image prompt generation using Claude API."""

import json
from typing import Optional

import httpx

from config import get_settings

settings = get_settings()

SCRIPT_PROMPT = """You are a short-form video scriptwriter for Dutch small businesses.

CLIENT CONTEXT:
- Business: {business_name}
- Offer: {what_they_sell}
- Audience: {target_customer}
- Differentiator: {what_makes_different}
- Tone: {tone}
- Language: {language}
- Topic focus: {topic}

TASK:
Write a 30–45 second video script for Instagram Reels / TikTok.

REQUIREMENTS:
- Strong hook in first 2 seconds
- Clear single message
- Call to action at end
- {language} language
- {tone} tone
- 5–7 scenes maximum

OUTPUT FORMAT:
Return ONLY valid JSON with no additional text:
{{
  "hook": "Opening line (2-3 seconds)",
  "scenes": [
    {{"text": "Scene 1 narration", "duration": 5}},
    {{"text": "Scene 2 narration", "duration": 6}}
  ],
  "cta": "Closing call to action",
  "total_duration": 35
}}"""

IMAGE_PROMPT_TEMPLATE = """You are a visual director for short-form video content.

SCRIPT:
{script_json}

BRAND CONTEXT:
- Industry: {industry}
- Style: Clean, modern, European, slightly desaturated

TASK:
Generate an image prompt for each scene. Images will be generated by Flux.

REQUIREMENTS:
- Photorealistic or clean illustration style
- No text in images
- Consistent visual style across all scenes
- Safe for work
- Appropriate for Dutch business audience

OUTPUT FORMAT:
Return ONLY valid JSON with no additional text:
{{
  "prompts": [
    {{"scene": 1, "prompt": "Detailed image prompt for scene 1..."}},
    {{"scene": 2, "prompt": "Detailed image prompt for scene 2..."}}
  ]
}}"""


async def generate_script(
    business_name: str,
    what_they_sell: str,
    target_customer: str,
    what_makes_different: str,
    tone: str = "friendly",
    language: str = "EN",
    topic: Optional[str] = None,
) -> dict:
    """
    Generate a video script using Claude API.

    Returns the script as a structured dict.
    """
    if not settings.anthropic_api_key:
        raise ValueError("ANTHROPIC_API_KEY not configured")

    prompt = SCRIPT_PROMPT.format(
        business_name=business_name,
        what_they_sell=what_they_sell,
        target_customer=target_customer,
        what_makes_different=what_makes_different,
        tone=tone,
        language=language,
        topic=topic or "general introduction",
    )

    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": settings.anthropic_api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 1000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60.0,
        )
        response.raise_for_status()

    result = response.json()
    content = result["content"][0]["text"]

    # Parse JSON from response
    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse script JSON: {e}\nContent: {content}")


async def generate_image_prompts(
    script: dict,
    industry: str = "general business",
) -> list[dict]:
    """
    Generate image prompts for each scene in a script.

    Returns a list of {scene, prompt} dicts.
    """
    if not settings.anthropic_api_key:
        raise ValueError("ANTHROPIC_API_KEY not configured")

    prompt = IMAGE_PROMPT_TEMPLATE.format(
        script_json=json.dumps(script, indent=2),
        industry=industry,
    )

    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": settings.anthropic_api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-sonnet-4-20250514",
                "max_tokens": 2000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60.0,
        )
        response.raise_for_status()

    result = response.json()
    content = result["content"][0]["text"]

    # Parse JSON from response
    try:
        data = json.loads(content)
        return data.get("prompts", [])
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse image prompts JSON: {e}\nContent: {content}")
